04-07-2022 12:29:50 error : Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: '' for column 'em_bank' at row 1
    at Query.Sequence._packetToError (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Pool.query (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Pool.js:199:23)
    at create (D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.service.js:5:14)
    at D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.controller.js:20:17
    at Query.<anonymous> (D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.service.js:234:24)
    at Query.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:149:8)
    at Query.EofPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:133:8)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
04-07-2022 12:31:43 error : Error: ER_DUP_ENTRY: Duplicate entry '' for key 'hrm_emp_personal.em_account_no_UNIQUE'
    at Query.Sequence._packetToError (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Pool.query (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Pool.js:199:23)
    at create (D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.service.js:5:14)
    at D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.controller.js:20:17
    at Query.<anonymous> (D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.service.js:234:24)
    at Query.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:149:8)
    at Query.EofPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:133:8)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
04-07-2022 12:33:44 error : Error: ER_DUP_ENTRY: Duplicate entry '' for key 'hrm_emp_personal.em_account_no_UNIQUE'
    at Query.Sequence._packetToError (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Pool.query (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Pool.js:199:23)
    at create (D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.service.js:5:14)
    at D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.controller.js:20:17
    at Query.<anonymous> (D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.service.js:234:24)
    at Query.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:149:8)
    at Query.EofPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:133:8)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
04-07-2022 12:34:17 error : Error: ER_DUP_ENTRY: Duplicate entry '10190100232641' for key 'hrm_emp_personal.em_account_no_UNIQUE'
    at Query.Sequence._packetToError (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Pool.query (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Pool.js:199:23)
    at create (D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.service.js:5:14)
    at D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.controller.js:20:17
    at Query.<anonymous> (D:\HR_BACKEND\hrm_baknd\api\hrm_emp_personal\emppersonal.service.js:234:24)
    at Query.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:149:8)
    at Query.EofPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:133:8)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
04-07-2022 12:44:32 error : Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`medi_hrm`.`hrm_emp_qual`, CONSTRAINT `EM_BOARD_FK` FOREIGN KEY (`em_board`) REFERENCES `hrm_board` (`board_slno`))
    at Query.Sequence._packetToError (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Pool.query (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Pool.js:199:23)
    at create (D:\HR_BACKEND\hrm_baknd\api\hrm_emp_qual\qualification.service.js:5:14)
    at createQual (D:\HR_BACKEND\hrm_baknd\api\hrm_emp_qual\qualification.controller.js:19:9)
    at Layer.handle [as handle_request] (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\route.js:137:13)
    at D:\HR_BACKEND\hrm_baknd\auth\token_validation.js:21:11
    at D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:94:10)
    at checkToken (D:\HR_BACKEND\hrm_baknd\auth\token_validation.js:8:11)
05-07-2022 11:28:55 error : Error: ER_BAD_FIELD_ERROR: Unknown column 'bank_status' in 'where clause'
    at Query.Sequence._packetToError (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Pool.query (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Pool.js:199:23)
    at getBankMaster (D:\HR_BACKEND\hrm_baknd\api\bankmaster\bank.service.js:100:14)
    at getBankMaster (D:\HR_BACKEND\hrm_baknd\api\bankmaster\bank.controller.js:158:9)
    at Layer.handle [as handle_request] (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\route.js:137:13)
    at D:\HR_BACKEND\hrm_baknd\auth\token_validation.js:21:11
    at D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:94:10)
    at checkToken (D:\HR_BACKEND\hrm_baknd\auth\token_validation.js:8:11)
05-07-2022 12:8:47 error : Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'bank_ifsc = 'FDRL0002288',
                    bank_address = 'travnacore medici' at line 4
    at Query.Sequence._packetToError (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Pool.query (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Pool.js:199:23)
    at update (D:\HR_BACKEND\hrm_baknd\api\bankmaster\bank.service.js:31:14)
    at updateBank (D:\HR_BACKEND\hrm_baknd\api\bankmaster\bank.controller.js:52:9)
    at Layer.handle [as handle_request] (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\route.js:137:13)
    at D:\HR_BACKEND\hrm_baknd\auth\token_validation.js:21:11
    at D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:94:10)
    at checkToken (D:\HR_BACKEND\hrm_baknd\auth\token_validation.js:8:11)
05-07-2022 12:8:55 error : Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'bank_ifsc = 'FDRL0002288',
                    bank_address = 'travnacore medici' at line 4
    at Query.Sequence._packetToError (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Pool.query (D:\HR_BACKEND\hrm_baknd\node_modules\mysql\lib\Pool.js:199:23)
    at update (D:\HR_BACKEND\hrm_baknd\api\bankmaster\bank.service.js:31:14)
    at updateBank (D:\HR_BACKEND\hrm_baknd\api\bankmaster\bank.controller.js:52:9)
    at Layer.handle [as handle_request] (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\route.js:137:13)
    at D:\HR_BACKEND\hrm_baknd\auth\token_validation.js:21:11
    at D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:94:10)
    at checkToken (D:\HR_BACKEND\hrm_baknd\auth\token_validation.js:8:11)
05-07-2022 4:30:34 error : TokenExpiredError: jwt expired
    at D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:94:10)
    at validateToken (D:\HR_BACKEND\hrm_baknd\api\users\user.controllers.js:10:17)
    at Layer.handle [as handle_request] (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\layer.js:95:5)
    at D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\index.js:335:12)
06-07-2022 6:12:20 error : TokenExpiredError: jwt expired
    at D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\HR_BACKEND\hrm_baknd\node_modules\jsonwebtoken\verify.js:94:10)
    at validateToken (D:\HR_BACKEND\hrm_baknd\api\users\user.controllers.js:10:17)
    at Layer.handle [as handle_request] (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\layer.js:95:5)
    at D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\HR_BACKEND\hrm_baknd\node_modules\express\lib\router\index.js:335:12)
15-07-2022 9:31:44 error : Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 5
    at Query.Sequence._packetToError (E:\InteliqoApi\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (E:\InteliqoApi\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (E:\InteliqoApi\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (E:\InteliqoApi\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (E:\InteliqoApi\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (E:\InteliqoApi\node_modules\mysql\lib\Pool.js:199:23)
    at update (E:\InteliqoApi\api\employeestatus\empstatus.service.js:27:14)
    at updateEmpStatus (E:\InteliqoApi\api\employeestatus\empstatus.controller.js:49:9)
    at Layer.handle [as handle_request] (E:\InteliqoApi\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\InteliqoApi\node_modules\express\lib\router\route.js:137:13)
    at E:\InteliqoApi\auth\token_validation.js:21:11
    at E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:94:10)
    at checkToken (E:\InteliqoApi\auth\token_validation.js:8:11)
15-07-2022 9:31:51 error : Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 5
    at Query.Sequence._packetToError (E:\InteliqoApi\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (E:\InteliqoApi\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (E:\InteliqoApi\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (E:\InteliqoApi\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (E:\InteliqoApi\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (E:\InteliqoApi\node_modules\mysql\lib\Pool.js:199:23)
    at update (E:\InteliqoApi\api\employeestatus\empstatus.service.js:27:14)
    at updateEmpStatus (E:\InteliqoApi\api\employeestatus\empstatus.controller.js:49:9)
    at Layer.handle [as handle_request] (E:\InteliqoApi\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\InteliqoApi\node_modules\express\lib\router\route.js:137:13)
    at E:\InteliqoApi\auth\token_validation.js:21:11
    at E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:94:10)
    at checkToken (E:\InteliqoApi\auth\token_validation.js:8:11)
15-07-2022 11:25:25 error : Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'em_designation =3,
                    em_from ='2021-01-01',
                  ' at line 6
    at Query.Sequence._packetToError (E:\InteliqoApi\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (E:\InteliqoApi\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (E:\InteliqoApi\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (E:\InteliqoApi\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (E:\InteliqoApi\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (E:\InteliqoApi\node_modules\mysql\lib\Pool.js:199:23)
    at update (E:\InteliqoApi\api\hrm_emp_exp\empexp.service.js:40:14)
    at updateExp (E:\InteliqoApi\api\hrm_emp_exp\empexp.controller.js:48:9)
    at Layer.handle [as handle_request] (E:\InteliqoApi\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\InteliqoApi\node_modules\express\lib\router\route.js:137:13)
    at E:\InteliqoApi\auth\token_validation.js:21:11
    at E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:94:10)
    at checkToken (E:\InteliqoApi\auth\token_validation.js:8:11)
15-07-2022 2:40:41 error : Error: ER_DUP_ENTRY: Duplicate entry '1' for key 'hrm_department_shift_master.sect_id_UNIQUE'
    at Query.Sequence._packetToError (E:\InteliqoApi\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (E:\InteliqoApi\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (E:\InteliqoApi\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (E:\InteliqoApi\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (E:\InteliqoApi\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (E:\InteliqoApi\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (E:\InteliqoApi\node_modules\mysql\lib\Pool.js:199:23)
    at create (E:\InteliqoApi\api\Departmentshiftmaster\Departmentshiftmaster.service.js:5:14)
    at create (E:\InteliqoApi\api\Departmentshiftmaster\Departmentshiftmaster.controller.js:17:9)
    at Layer.handle [as handle_request] (E:\InteliqoApi\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\InteliqoApi\node_modules\express\lib\router\route.js:137:13)
    at E:\InteliqoApi\auth\token_validation.js:21:11
    at E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (E:\InteliqoApi\node_modules\jsonwebtoken\verify.js:94:10)
    at checkToken (E:\InteliqoApi\auth\token_validation.js:8:11)
